services:
  whatsapper:
    image: baldarn/whatsapper
    build:
      context: .
    container_name: whatsapper
    volumes:
      - ./app:/app
      - whatsapper:/data
    ports:
      - 4000:3000

volumes:
  whatsapper:
